<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Library</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Data.Sqlite" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SRN.CC.Core\SRN.CC.Core.csproj" />
    <ProjectReference Include="..\SRN.CC.Formats\SRN.CC.Formats.csproj" />
  </ItemGroup>
</Project>
